name: "Bug Report"
description: Create a new ticket for a bug.
title: "[BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter step-by-step instructions to reproduce the issue
      render: bash
      placeholder: "Provide step-by-step instructions to reproduce the issue"
    validations:
      required: true    
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Copy and paste relevant log output with Debug mode enabled (log level).
      render: bash
      placeholder: Clear any tokens or sensitive data before submitting.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: "Version"
      description: What version of the software are you using?
      placeholder: e.g., v1.2.3
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: Add any other context about the problem here, including screenshots if applicable
    validations:
      required: false