# MkDocs configuration for twitch.py documentation
site_name: twitch.py
site_description: Python library for Twitch API and real-time WebSocket EventSub
site_author: Snifo
site_url: https://twitchpy.readthedocs.io
docs_dir: src

# Repository information
repo_url: https://github.com/mrsnifo/twitch.py
repo_name: mrsnifo/twitch.py
copyright: Copyright (c) 2025-present mrsnifo

# Theme configuration
theme:
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  icon:
    logo: material/broadcast
    repo: fontawesome/brands/github

  # Custom directory for template overrides
  custom_dir: overrides

  # Twitch-inspired purple color scheme
  palette:
    - media: "(prefers-color-scheme)"
      primary: purple
      accent: deep purple
      toggle:
        icon: material/link
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference

  # Essential features
  features:
    - navigation.top
    - navigation.tabs
    - search.highlight
    - content.code.copy
    - navigation.path
    - navigation.prune

# Site navigation
nav:
  - Getting started:
      - 'index.md'
      - Concepts: 'concepts.md'
      - Quickstart: 'quickstart.md'
  - Reference:
      - App: 'reference/app/app.md'
      - Classes: 'reference/app/classes.md'
      - Errors: 'reference/app/errors.md'
      - Models: 'reference/app/models.md'
      - Utils: 'reference/app/utils.md'
  - Eventsub:
      - 'reference/eventsub/index.md'
      - Client: 'reference/eventsub/client.md'
      - Classes: 'reference/eventsub/classes.md'
      - Models: 'reference/eventsub/models.md'
      - Errors: 'reference/eventsub/errors.md'
      - Debug: 'reference/eventsub/debug.md'
  - Oauth:
      - Flows: 'reference/oauth/flows.md'
      - Scopes: 'reference/oauth/scopes.md'
      - Models: 'reference/oauth/models.md'
  - Extensions:
      - Tasks: 'ext/tasks.md'

# Markdown processing
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

# Documentation plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          paths: [.., twitch]
          options:
            inherited_members: true
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            members_order: source
            annotations_path: source
            docstring_style: numpy
            docstring_section_style: spacy
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_bases: true
            show_submodules: true
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            preload_modules: [ twitch ]
            allow_inspection: true
            filters:
              - "!^_"
              - "!^test_"
            extra:
              Extensions:
                - griffe.extensions.dataclasses
                - griffe.extensions.hybrid
              load_external_modules: true
